version: "3.8"

services:
  mysql_db:
    image: mysql:5.7  
    env_file:
        - .env
    environment:
      MYSQL_DATABASE: ${MYSQL_DATABASE}  
      MYSQL_USER: ${MYSQL_USER}  
      MYSQL_PASSWORD: ${MYSQL_PASSWORD} 
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}  
    ports:
      - "3308:3306"  
    command: --init-file /docker-entrypoint-initdb.d/create_schema.sql
    restart: always  
    container_name: ${MYSQL_CONTAINER_NAME}
    volumes:
      - db_data:/var/lib/mysql
      - ./init:/docker-entrypoint-initdb.d/

  flask_app: 
    build:   
      context: .
      dockerfile: Dockerfile
    ports:
      - "5005:5005" 
    
    volumes:
      - .:/EFIdevOpsPython
    env_file:
      - .env
    depends_on:
      - mysql_db
    container_name: flask_app_c



volumes:
  db_data: